name: Github Action for Typst
description: GitHub Action to compile typst documents
author: Louis Vignoli
branding:
  icon: book-open
  color: blue

inputs:
  source_file:
    description: The typst file to be compiled. There can be multiple ones separated by new lines.
    required: true
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.source_file }}
