name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Self test
        id: selftest
        uses: lvignoli/typst-action@develop
        with:
          source_file: |
            tests/valid.typ
            tests/math.typ
          options: |
            --font_dir fonts
            --verbose 3
      - name: Check existence of output file
        run: |
          test -e "tests/valid.pdf"
          test -e "tests/math.pdf"
      # - name: Test options
